#!/usr/bin/env ruby


def display_main_menu
    menu =<<EOS
Welcome!
--------------------
What would you like to do?
1. Select an Existing Budget
2. Create a New Budget
--------------------
Type 'Q' to Quit
--------------------
Select a Number:
EOS
  puts menu
  user_selection = gets.chomp
  if user_selection == 'Q' or user_selection == 'q'
    quit_selected
  elsif user_selection == '1'
    puts 'Select an Existing Budget'
  elsif user_selection == '2'
    puts 'Create a New Budget'
  else
    puts 'Invalid Selection'
    display_main_menu
  end
end

def quit_selected
  puts "Goodbye!"
end


display_main_menu
